### PR TITLE
Update index.js: JSONField moved to django models

### PR DESCRIPTION
**Pull request by nikolaysm**
Since **Django 3.1** `JSONField` moved to `django.db.models`.

Django 3.1  includes models.JSONField and forms.JSONField that can be used on all supported database backends.

Source: [https://docs.djangoproject.com/en/dev/releases/3.1/#jsonfield-for-all-supported-database-backends](https://docs.djangoproject.com/en/dev/releases/3.1/#jsonfield-for-all-supported-database-backends)

### CODE REVIEW

**Comment by mmcardle** [comment]
Thanks, 

Although this will break Django2, Django 2 is no longer supported so happy to merge 
https://www.djangoproject.com/download/

M

**Comment by nikolaysm** [comment]
Hi @mmcardle,

Yes, you are right. Extended support for **Django 2.2 LTS ** ended on April 11, 2022.

Thanks for merging.

**Comment by nikolaysm** [comment]
Hi @mmcardle ,

Thanks again for merging.

Do you have any idea when djangobuilder.io will be updated?

**Comment by mmcardle** [comment]
> Hi @mmcardle ,
> 
> Thanks again for merging.
> 
> Do you have any idea when djangobuilder.io will be updated?

Should be done now :)

**Pull request merged**
